### ISSUE TITLE
separate prefix for module?

### ISSUE THREAD

**Issue by torehl** [hjelmn/xpmem#35]
Hi,

    when building xpmem for module environment with  ./configure --prefix=/cm/shared/apps/xpmem/2.6.5  the module installs to /cm/shared/apps/xpmem/2.6.5/lib/modules/`uname -r`

    Is it possible to add kernel module install path that is separate to the prefix install path? 

torel@n005:~/workspace/XPMEM/xpmem-2.6.5-aarch64/kernel$ egrep -i -e "libdir|kerneldir|moduledir" Makefile
pkglibdir = $(libdir)/xpmem
am__installdirs = "$(DESTDIR)$(initdir)" "$(DESTDIR)$(moduledir)"
kerneldir = /lib/modules/4.15.0-117-generic/build/
libdir = ${exec_prefix}/lib
moduledir = $(libdir)/modules/4.15.0-117-generic/

Brgds,
Tor

**Comment by hjelmn** [comment]
Sure. I will look into that today.

**Comment by hjelmn** [comment]
Done. Added ```--with-module-prefix```. I also modified make install to run ```depmod -a``` so that the new module will be picked up by modprobe.
