### ISSUE TITLE
Add a LGPL or BSD licensed version of libxpmem

### ISSUE THREAD

**Issue by hjelmn** [hjelmn/xpmem#6]
I am talking to Cray and will engage SGI to see about relicensing the library as LGPL. If that is impossible a new library will have to be written.

**Comment by shamisp** [comment]
Lgpl only solves the problem for libraries and not compilers, which not good enough for our use case.

**Comment by hjelmn** [comment]
Would full BSD be preferable?

**Comment by shamisp** [comment]
For the user level - indeed.

**Comment by jdinan** [comment]
+1 for BSD.

**Comment by shamisp** [comment]
Just to be clear - user level BSD, kernel level GPL.

**Comment by hjelmn** [comment]
Exactly. Re-writing the kernel driver would be a nightmare. The library wouldn't be too bad.

**Comment by shamisp** [comment]
We don't need multiple proprietary drivers doing exactly the same...

**Comment by jdinan** [comment]
Right, IIUC, user-level BSD is needed for BSD-licensed libraries to use XPMEM.  Is that right?

**Comment by shamisp** [comment]
Correct..

**Comment by hjelmn** [comment]
Ok, they approved LGPL. I think either I had brought this up with them earlier or some other customer did. I will update the licensing to reflect the weakening of the license. I asked about BSD. Will have to see what they say.

**Comment by jdinan** [comment]
Ignore my earlier comment about needing user-level with BSD license for BSD-licensed libraries.  It should be totally fine to link a BSD library with an LGPL library.  BSD is probably easier, but this usage model is one of the reasons why LGPL was created.

**Comment by hjelmn** [comment]
Waiting on confirmation from Cray on what they did to relicense. Should know later this week.
